print('===== Desafio 004 ======')
algo = input('Digite algo: ')
print('o tipo primitivo dese valor é:', type(algo))
print('só tem espaços?', algo.isspace())
print('está em maiúsculo?', algo.isupper())
print('está em minúsculo?', algo.islower())
print('é numerico?', algo.isnumeric())
