print('+' * 70)
nome = str(input('Escreva o nome completo: ')).strip().title()
n = nome.split()
print('Seu primeiro nome é {}'.format(n[0]))
print('Seu último nome é {}'.format(n[len(n) - 1]))
print('-' * 70)
