print('-=-' * 30)
print('-=-' * 30)
print('++-- FINANCIAMENTO IMOBILIÁRIO --++')
print('*' * 35)
valor = float(input('Valor da casa: R$ '))
salario = float(input('Qual o salário: R$ '))
anos = int(input('Quantos anos para pagrar? '))
print('*' * 35)
mensalidade = (valor / (anos * 12))
porcen = (salario * 0.30)
print('Mensalidade: R$ {:.2f}'.format(mensalidade))
print('30% do salário: R$ {:.2f}'.format(porcen))
print('*' * 35)
if mensalidade >= porcen:
    print('A mensalidade é maior que R$ {:.2f}. NÃO PODERÁ FINANCIAR'.format(porcen))
else:
    print('A mensalida é menor que R$ {:.2f}. FINANCIAMENTO LIBERADO'.format(porcen))
print('-=-' * 30)
print('-=-' * 30)
